name: BallsOfSteel
main: com.cubesoflegend.ballsofsteel.Main
version: 0.0.1
depend: [MinigamesLib]
commands:
   bos:
      description: Commande de test
      usage: /<command>
      permission: <plugin name>.basic
      permission-message: You don't have <permission>